<?php
/**
 * Handles enqueueing assets for the admin interface.
 *
 * @package MenuGhost
 */

declare(strict_types=1);

namespace MenuGhost\Admin\Assets;

use MenuGhost\Admin\DataProvider;
use MenuGhost\SettingsRepository;
use function get_current_screen;
use function add_action;
use function admin_url;
use function wp_create_nonce;
use function wp_enqueue_script;
use function wp_enqueue_style;
use function wp_localize_script;
use function wp_style_add_data;
use function wp_set_script_translations;

/**
 * Handles registering and enqueueing admin assets.
 *
 * @since 1.1.0
 */
class AdminAssets {
	/**
	 * Register the hooks required to load assets.
	 *
	 * @since 1.1.0
	 *
	 * @return void
	 */
	public static function register(): void {
		$instance = new self();

		add_action( 'admin_enqueue_scripts', array( $instance, 'enqueue' ) );
		add_action( 'enqueue_block_editor_assets', array( $instance, 'enqueue_block_editor' ) );
	}

	/**
	 * Enqueue assets for the nav menu screen.
	 *
	 * @since 1.1.0
	 *
	 * @param string $hook_suffix Current admin page suffix.
	 *
	 * @return void
	 */
	public function enqueue( string $hook_suffix ): void {
		if ( 'nav-menus.php' !== $hook_suffix ) {
			return;
		}

		$asset_file = include MNGH_BUILD_DIR . 'index.asset.php';

		$this->enqueue_scripts( $asset_file );
		$this->enqueue_styles( $asset_file );

		wp_enqueue_style( 'wp-components' );

		$this->localize_script();
	}

	/**
	 * Enqueue assets inside the block editor (navigation block / site editor).
	 *
	 * @return void
	 */
	public function enqueue_block_editor(): void {
		$screen = get_current_screen();

		if ( ! $screen ) {
			return;
		}

		// Only load for navigation editor contexts.
		$is_navigation_editor = 'wp_navigation' === ( $screen->post_type ?? '' ) || 'site-editor' === ( $screen->id ?? '' );

		if ( ! $is_navigation_editor ) {
			return;
		}

		$asset_file = include MNGH_BUILD_DIR . 'index.asset.php';

		$this->enqueue_scripts( $asset_file );
		$this->enqueue_styles( $asset_file );

		// Minimal data needed in the block editor; menu items/saved settings are fetched per link.
		$this->localize_script( array(), array() );
	}

	/**
	 * Enqueue the admin script.
	 *
	 * @since 1.1.0
	 *
	 * @param array<string,mixed> $asset_file Asset metadata generated by the build step.
	 *
	 * @return void
	 */
	private function enqueue_scripts( array $asset_file ): void {
		wp_enqueue_script(
			'mngh-admin-script',
			MNGH_BUILD_URL . 'index.js',
			(array) ( $asset_file['dependencies'] ?? array() ),
			(string) ( $asset_file['version'] ?? MNGH_VERSION ),
			true
		);

		wp_set_script_translations(
			'mngh-admin-script',
			'menu-ghost',
			MNGH_DIR . 'languages'
		);
	}

	/**
	 * Enqueue the admin stylesheet.
	 *
	 * @since 1.1.0
	 *
	 * @param array<string,mixed> $asset_file Asset metadata generated by the build step.
	 *
	 * @return void
	 */
	private function enqueue_styles( array $asset_file ): void {
		wp_enqueue_style(
			'mngh-admin-style',
			MNGH_BUILD_URL . 'index.css',
			array(),
			(string) ( $asset_file['version'] ?? MNGH_VERSION )
		);

		wp_style_add_data( 'mngh-admin-style', 'rtl', 'replace' );
	}

	/**
	 * Localize data required by the admin script.
	 *
	 * @since 1.1.0
	 *
	 * @param array<int,array<string,mixed>>|null $menu_items     Optional precomputed menu items.
	 * @param array<int,array<string,mixed>>|null $saved_settings Optional precomputed saved settings.
	 *
	 * @return void
	 */
	private function localize_script( ?array $menu_items = null, ?array $saved_settings = null ): void {
		$menu_items    = null === $menu_items ? DataProvider::generate_menu_items_data() : $menu_items;
		$menu_item_ids = array_map(
			static fn( array $menu_item ): int => (int) ( $menu_item['id'] ?? 0 ),
			$menu_items
		);

		$page_conditions   = DataProvider::generate_page_conditions();
		$additional_lookup = DataProvider::build_additional_lookup( $page_conditions['scopes'] ?? array() );
		$saved_settings    = null === $saved_settings ? SettingsRepository::get_many( $menu_item_ids ) : $saved_settings;

		foreach ( $saved_settings as $menu_id => $settings ) {
			if ( empty( $settings['pages'] ) || ! is_array( $settings['pages'] ) ) {
				continue;
			}

			$saved_settings[ $menu_id ]['pages'] = DataProvider::populate_additional_labels(
				$settings['pages'],
				$additional_lookup
			);
		}

		wp_localize_script(
			'mngh-admin-script',
			'mnghMenuGhost',
			array(
				'menu_items'      => $menu_items,
				'page_conditions' => $page_conditions,
				'advanced_meta'   => DataProvider::generate_advanced_meta(),
				'saved_settings'  => $saved_settings,
				'ajax_url'        => admin_url( 'admin-ajax.php' ),
				'nonce'           => wp_create_nonce( 'menu_ghost' ),
			)
		);
	}
}
